repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: clang-format
        name: clang-format
        entry: clang-format -i
        language: system
        types_or: [c++, c, header]
      - id: clang-tidy
        name: clang-tidy
        entry: clang-tidy -p build/dev-clang
        language: system
        types_or: [c++]
        exclude: ^tests/

