# Profile-Guided Optimization (PGO) and ThinLTO for Execore
function(execore_configure_pgo target_name)
    option(EXECORE_ENABLE_THINLTO "Enable ThinLTO cross-module inlining" OFF)
    set(EXECORE_PGO_MODE "OFF" CACHE STRING "PGO Mode: OFF, GENERATE, USE")

    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        if(EXECORE_ENABLE_THINLTO)
            if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
                target_compile_options(${target_name} PRIVATE -flto=thin)
                target_link_options(${target_name} PRIVATE -flto=thin)
            else()
                target_compile_options(${target_name} PRIVATE -flto=auto)
                target_link_options(${target_name} PRIVATE -flto=auto)
            endif()
            message(STATUS "Execore [${target_name}]: ThinLTO enabled")
        endif()

        if(EXECORE_PGO_MODE STREQUAL "GENERATE")
            set(PGO_DIR "${CMAKE_BINARY_DIR}/pgo_profiles")
            file(MAKE_DIRECTORY ${PGO_DIR})
            if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
                target_compile_options(${target_name} PRIVATE -fprofile-instr-generate=${PGO_DIR}/code-%p.profraw)
                target_link_options(${target_name} PRIVATE -fprofile-instr-generate=${PGO_DIR}/code-%p.profraw)
            else()
                target_compile_options(${target_name} PRIVATE -fprofile-generate=${PGO_DIR})
                target_link_options(${target_name} PRIVATE -fprofile-generate=${PGO_DIR})
            endif()
            message(STATUS "Execore [${target_name}]: PGO instrumentation active (output: ${PGO_DIR})")
        elseif(EXECORE_PGO_MODE STREQUAL "USE")
            set(PGO_DIR "${CMAKE_BINARY_DIR}/pgo_profiles")
            if(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
                set(PROF_DATA "${PGO_DIR}/merged.profdata")
                target_compile_options(${target_name} PRIVATE -fprofile-instr-use=${PROF_DATA})
                target_link_options(${target_name} PRIVATE -fprofile-instr-use=${PROF_DATA})
            else()
                target_compile_options(${target_name} PRIVATE -fprofile-use=${PGO_DIR})
                target_link_options(${target_name} PRIVATE -fprofile-use=${PGO_DIR})
            endif()
            message(STATUS "Execore [${target_name}]: PGO profile utilization active")
        endif()
    endif()
endfunction()
