# Multi-Sanitizer Matrix configuration for Execore (ASan, UBSan, TSan, MSan)
macro(execore_setup_sanitizers)
    option(EXECORE_ENABLE_ASAN "Enable AddressSanitizer & LeakSanitizer" OFF)
    option(EXECORE_ENABLE_UBSAN "Enable UndefinedBehaviorSanitizer" OFF)
    option(EXECORE_ENABLE_TSAN "Enable ThreadSanitizer" OFF)
    option(EXECORE_ENABLE_MSAN "Enable MemorySanitizer" OFF)

    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang|GNU")
        set(SANITIZERS "")

        if(EXECORE_ENABLE_TSAN)
            list(APPEND SANITIZERS "thread")
        elseif(EXECORE_ENABLE_MSAN)
            list(APPEND SANITIZERS "memory")
        else()
            if(EXECORE_ENABLE_ASAN)
                list(APPEND SANITIZERS "address")
                if(NOT APPLE AND NOT WIN32)
                    list(APPEND SANITIZERS "leak")
                endif()
            endif()

            if(EXECORE_ENABLE_UBSAN)
                list(APPEND SANITIZERS "undefined")
            endif()
        endif()

        list(JOIN SANITIZERS "," SANITIZERS_LIST)

        if(NOT "${SANITIZERS_LIST}" STREQUAL "")
            add_compile_options(-fsanitize=${SANITIZERS_LIST} -fno-omit-frame-pointer)
            if(EXECORE_ENABLE_UBSAN)
                add_compile_options(-fno-sanitize-recover=all)
            endif()
            add_link_options(-fsanitize=${SANITIZERS_LIST})
            message(STATUS "Execore Global Sanitizers enabled: ${SANITIZERS_LIST}")
        endif()
    endif()
endmacro()

function(execore_enable_sanitizers target_name)
    # Global options are configured via execore_setup_sanitizers()
endfunction()
